name: deploy app

on:
  push:
    branches:
      - dev
      - main
    paths:
      - "app/**"
      - ".github/workflows/app.yml"

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: us-east1

jobs:
  setup-build-deploy:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: set env to dev
        if: endsWith(github.ref, '/dev')
        run: |
          echo "SERVICE_NAME=app-dev" >> "$GITHUB_ENV"
          echo "NEXT_PUBLIC_STRAPI_API_URL=https://api-dev.cantodaruaemergencial.com.br" >> "$GITHUB_ENV"
          echo "STORAGE_BUCKET=gs://dev.cantodaruaemergencial.com.br" >> "$GITHUB_ENV"
      - name: set env to production
        if: endsWith(github.ref, '/main')
        run: |
          echo "SERVICE_NAME=app" >> "$GITHUB_ENV"
          echo "NEXT_PUBLIC_STRAPI_API_URL=https://api.cantodaruaemergencial.com.br" >> "$GITHUB_ENV"
          echo "STORAGE_BUCKET=gs://www.cantodaruaemergencial.com.br" >> "$GITHUB_ENV"
      - name: checkout
        uses: actions/checkout@v1

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: "275.0.0"
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      - name: gcloud Set up
        run: |
          gcloud config set project $PROJECT_ID

      - name: build and deploy
        run: |
          cd app
          yarn && yarn build
          gsutil -m rsync -r -d out $STORAGE_BUCKET          
